apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    client.knative.dev/user-image: australia-southeast1-docker.pkg.dev/qscope/main/quickscope:latest
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
  labels:
    cloud.googleapis.com/location: australia-southeast1
  name: quickscope
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containerConcurrency: 80
      containers:
      - image: australia-southeast1-docker.pkg.dev/qscope/main/quickscope:latest
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
