name: Build container and deploy application
on: push
jobs:
  build-push:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Login to GAR 
        uses: docker/login-action@v1
        with:
          registry: australia-southeast1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: australia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/main/quickscope:latest