name: Build container and deploy application
on: 
  push:
    branches:
      - main
jobs:
  build-push:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Login to GAR 
        uses: docker/login-action@v1
        with:
          registry: australia-southeast1-docker.pkg.dev
          username: _json_key
          password: $${{secrets.GCP_GAR_ADMIN }}
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 
            - $${{ secrets.GCP_ARTIFACT_REPOSITORY_URL }}/quickscope:latest
            - $${{ secrets.GCP_ARTIFACT_REPOSITORY_URL }}/quickscope:{{ env.GITHUB_SHA_SHORT }}
