name: Build container and deploy application
on: push
jobs:
  build-push:
    runs-on: ubuntu-latest
    environment: production
    env:
      IMAGE_TAG: australia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/main/quickscope:latest
    steps:
      - name: Login to GAR 
        uses: docker/login-action@v1
        with:
          registry: australia-southeast1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMAGE_TAG }}
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: quickscope
          image: ${{env.IMAGE_TAG }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          region: australia-southeast1
