name: Build container and deploy application
on: workflow_dispatch
jobs:
  build-push:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Login to GAR 
        uses: docker/login-action@v1
        with:
          registry: australia-southeast1-docker.pkg.dev
          username: _json_key
          password: $${{secrets.GCP_GAR_ADMIN }}